### ISSUE TITLE
Mouse bindings over icon not working

### ISSUE THREAD

**Issue by abacao** [christophgysin/pasystray#102]
The only actions that works is scroll up and down.

The x marks whats woking.

> over status icon:
> 
> - [x] left/right-click: open menu
> - [ ] ctrl + left-click: start pavucontrol
> - [ ] middle-click / alt + left-click: toggle mute default sink
> - [ ] ctrl + middle-click / ctrl + alt + left-click: toggle mute default source
> - [x] scroll up/down: adjust the default sink volume
> - [ ] ctrl + scroll: adjust the default source volume

Would like to provide more info, please let me know what you need.

In another note, why are improvments in code and no new release?

**Comment by abacao** [comment]
@christophgysin maybe. I'm in fact using Ubuntu but with the i3wm instead (again, if I can provide more info, please tell me how).
I am also happy with the version 0.6.0 but a new release will show that this software is being maintained and thank you for that!
Thank you

**Comment by wb9688** [comment]
I also have the problem that all bindings except left/right-click and scrolling don't work, while it has worked before on my systems running Debian GNU/Linux Unstable with Openbox and Tint2.

**Comment by vblo** [comment]
@christophgysin: I filled a bug report in `libayatana-appindicator` (a fork of `libappindicator` that is not ubuntu-specific and is used in particular in debian) so the necessary events are available. In the meantime, an option would be to prefer `GtkStatusIcon` over `AppIndicator` in `pasystray`, by moving the `HAVE_APPINDICATOR` section below the `HAVE_STATUSICON` section in `systray_impl.c`.

**Comment by christophgysin** [comment]
@vblo You can just build pasystray with:
```
./configure --disable-appindicator
```
It's up the the distributions' package maintainer to choose what libraries to build pasystray against. So I suggest you file a bug with debian, or build the package yourself from source.

**Comment by vblo** [comment]
Right. I'll file a bug to debian. Thanks.

**Comment by smlx** [comment]
As I understand it, middle click functionality can be enabled under appindicator (in Gnome Shell, at least) by [setting the secondary-activate target](https://github.com/AyatanaIndicators/libayatana-appindicator/blob/b14ba3324a7f80ff4fcc5025b576d33544178f74/src/app-indicator.c#L2259). The limitation here is that it can only activate a menu item, rather than arbitrary functionality.

There's a good description of secondary-activate in this issue https://github.com/linuxmint/Cinnamon/issues/6901

**Comment by EmilyBjoerk** [comment]
I'm not sure if this is related but I cannot scroll on the volume icon to change the volume. 

Gentoo, MATE w/ i3wm
[ebuild   R   ~] media-sound/pasystray-0.7.0::gentoo  USE="libnotify zeroconf" 0 KiB

**Comment by czerw** [comment]
I have/had exactly same issue on openSUSE Tumbleweed.  All mouse bindings started to work again, when I disabled appindicator support during the build.

**Comment by christophgysin** [comment]
@czerw Could you please open a bug with OpenSUSE? pasystray supports multiple systray backends, it's up to the distro packager to choose the most suitable one.

**Comment by czerw** [comment]
@christophgysin I will fix it there by my self.
