### ISSUE TITLE
[Feature Request] Playback Stream with a better naming

### ISSUE THREAD

**Issue by abacao** [christophgysin/pasystray#105]
Hello,

https://ibb.co/hYaVHq

Is it possible to better identify witch playback stream window is related?
In the image provided, I have 2 firefox windows, both with audio and with different tittle names.

Is it possible to use the window title bar name to identify the playback stream?

Suggestion:
[localhost] How To Cook Perfect Eggs Every Time - YouTube - Firefox
[192.168.10.101] How To Bake Perfect Desserts - YouTube - Firefox

**Comment by thetoastcaper** [comment]
The names shown are what's provided to PulseAudio by the client application. Pasystray is accurately displaying the stream's titles according to the PulseAudio server. Optimally, providing more accurate titles should probably be the application developer's responsibility.

That aside, the prospect of automatically inferring more accurate titles would probably be something left to a PulseAudio module if anything? Though, with the woefully limited information that most clients provide to PulseAudio, that in itself would probably wind up unreliable at best

This is all to my (incomplete) knowledge though, so I may not be entirely correct on all this!

**Comment by rohieb** [comment]
Yes, the stream title is provided by pulseaudio, so there is nothing we can do about it in pasystray.
