### ISSUE TITLE
Volume increments are twice the size they should be

### ISSUE THREAD

**Issue by mcz** [christophgysin/pasystray#110]
When changing the volume by scrolling the mouse wheel over the systray icon, the increment is twice the size specified with the `--volume-inc` option (e.g. when `--volume-inc=5`, scrolling changes volume in steps of 10).
When no `--volume-inc` is specified, the volume changes in steps of 2 instead of 1 as set in _options.c_.

**Comment by christophgysin** [comment]
The problem seems to be here:
https://github.com/christophgysin/pasystray/blob/master/src/pulseaudio_action.c#L162

We could change that to 1% steps, and change the default volume_inc to 2. That would keep the current default behaviour.

Wanna make a PR?
