### ISSUE TITLE
volume-max not working

### ISSUE THREAD

**Issue by JohnHatNeDVD** [christophgysin/pasystray#114]
there is an option, that obviously works not properly.
--volume-max=200
should expand the maximum of the bar in the notification.
Hardcoding in notify.c is possible but non-dynamic in lines 60 and 72
notify_notification_set_hint_int32 (n, "value", value);
by replacing value by value/2 - it does volume-max=200 on the notification.
"value/volume_max" does not work, because volume_max is defined in options.c and I don't know how to connect these to get the var (parsed option) in notifiy.c

**Comment by christophgysin** [comment]
@JohnHatNeDVD Can you test if the commit above fixes this for you?

**Comment by JohnHatNeDVD** [comment]
int volume is not defined, compiling fails

**Comment by JohnHatNeDVD** [comment]
Tested with several volume-max values successfully. This solves the problem. :)
