### ISSUE TITLE
add pulseaudio-equalizer to systray-menu

### ISSUE THREAD

**Issue by JohnHatNeDVD** [christophgysin/pasystray#116]
To add equalizer (qpaeq) to menu, add in systray.c

31:
+ static const char* COMMAND_PAEQ = "qpaeq";

56:
+     systray_menu_add_application(mis->menu, "_Equalizer...", NULL, COMMAND_PAEQ);

PLUS: optional dependency qpaeq in PKGBUILD

**Comment by christophgysin** [comment]
Do you think you could try to create a pull request?

**Comment by JohnHatNeDVD** [comment]
I tried, hopefully I did that correctly.

**Comment by christophgysin** [comment]
Thanks!
