### ISSUE TITLE
Segmentation fault on PipeWire

### ISSUE THREAD

**Issue by wundrweapon** [christophgysin/pasystray#145]
Whne Pulse is launched via `pipewire-pulse`, pasystray fails to launch with a segmentation fault. The only other information printed to the terminal are a Gtk-WARNING marked "Theme parsing error" and a Gtk-CRITICAL marked "assertion 'GTK_IS_WIDGET (widget)' failed".

Other Pulse applications, such as Discord, pavucontrol, and Steam games on Proton, work as expeted.

**Comment by christophgysin** [comment]
I'm pretty sure this is a duplicate of #90.
