### ISSUE TITLE
Feature request: Add notifications

### ISSUE THREAD

**Issue by Scorpion2185** [christophgysin/pasystray#146]
Can you add notifications? For example when changing the volume with a shortcut.

**Comment by christophgysin** [comment]
Have you tried `--notify=all`?

```
$ pasystray --notify help
Notification options:
  all                     Notify for all detected changes
  none                    Never notify, except for options set after this one
  new                     Notify when new sinks/sources are added
  sink                    Notify for changes to all sinks
  sink_default            Notify for changes to the default sink
  source                  Notify for changes to all sources
  source_default          Notify for changes to the default source
  stream                  Notify for all streams
  stream_output           Notify for output (playback) streams
  stream_input            Notify for input (recording) streams
  systray_action          Notify for changes made through pasystray
  help                    List possible options and exit

**Comment by Scorpion2185** [comment]
I didn't know about CLI options, I only checked the GUI.
Nice!

**Comment by Scorpion2185** [comment]
I didn't know about CLI options, I only checked the GUI.
Nice!
Is there a setting to prevent pasystray to start automatically so I can launch it with the `--notify=all`?
But I can just add `pasystray --notify=all` to startup applications, right?

**Comment by Scorpion2185** [comment]
I didn't know about CLI options, I only checked the GUI.
Nice!
Is there a setting to prevent pasystray to start automatically so I can launch it with the `--notify=all` option?
If I add `pasystray --notify=all` to autostart I end with 2 pasystray.

Do I have to manually remove `/etc/xdg/autostart/pasystray.desktop`?

**Comment by christophgysin** [comment]
You can just edit pasystray.desktop:
```
Exec=pasystray --notify=all

**Comment by Scorpion2185** [comment]
Right I didn't think about it.
I think that pasystray should have an option to avoid autostart so users can disable it without editing files in the /, needing admin rights.
Something that you can change in dconf for your user.

**Comment by christophgysin** [comment]
This is all specified by the [XDG autostart specification](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html)

System-wide desktop entries can be overridden by user-specific entries with the same filename. To disable a system-wide entry, create an overriding entry containing `Hidden=true`.

**Comment by Scorpion2185** [comment]
Can I use that for the Openbox autostart? 

Is this correct for the universal autostart? `OnlyShowIn=openbox;`.

A nice feature could be an option in the GUI to add/remove some or all the notifications.

**Comment by Scorpion2185** [comment]
I can't add that to the Openbox autostart though. 
And if you want that the app doesn't start automatically, can you do it with a user-specific entry?

A nice feature could be an option in the GUI to add/remove some or all the notifications.

**Comment by christophgysin** [comment]
> I can't add that to the Openbox autostart though.
And if you want that the app doesn't start automatically, can you do it with a user-specific entry?

Exactly. You use a user-specific entry to either change the CLI options pasystray is started with, or completely disable it with the above exanple.

What's your usecase for changing notification options at runtime? If you create a PR I will consider applying it.

**Comment by Scorpion2185** [comment]
I would have avoided to make a custom entry to add the `--notify=all` option.
If you get tired of some notifications or you want to add some to check something you can do it on the fly without using the entries.
