### ISSUE TITLE
Lost icon after upgrade to 0.8.0-1

### ISSUE THREAD

**Issue by sbbddz** [christophgysin/pasystray#151]
Hi, today I noticed that after updating my system (running Arch Linux with dwm as my window manager) pasystray icon disappear from my system tray.

Here is the before and the after:
![before_update_pasystray](https://user-images.githubusercontent.com/5954310/140990585-4c554a26-677a-4d4a-a998-a40a9c7fab89.png) **>>>** ![after_update_pasystray](https://user-images.githubusercontent.com/5954310/140990602-af8b66cd-e817-403f-910b-f2ad4c6fe211.png)
Icon however, still works and its clickable. Haven't tested it in another desktop environment or window manager. Still possible to be some kind of issue with my setup, I'll continue researching.

Version not working: **0.8.0-1** Arch Linux with dwm as window manager
Version working: **0.7.1**

Thanks for your attention!

**Comment by stm28304** [comment]
Same here. I use arch also; but openbox.

**Comment by kofm** [comment]
> Hi, today I noticed that after updating my system (running Arch Linux with dwm as my window manager) pasystray icon disappear from my system tray.
> 
> Here is the before and the after: ![before_update_pasystray](https://user-images.githubusercontent.com/5954310/140990585-4c554a26-677a-4d4a-a998-a40a9c7fab89.png) **>>>** ![after_update_pasystray](https://user-images.githubusercontent.com/5954310/140990602-af8b66cd-e817-403f-910b-f2ad4c6fe211.png) Icon however, still works and its clickable. Haven't tested it in another desktop environment or window manager. Still possible to be some kind of issue with my setup, I'll continue researching.
> 
> Version not working: **0.8.0-1** Arch Linux with dwm as window manager Version working: **0.7.1**
> 
> Thanks for your attention!

Exactly the same for me, tried changing icon theme but it always pick up light version 
![image](https://user-images.githubusercontent.com/12545394/141076759-d3d8d68f-b0bb-4251-900d-6e1f600fc9cf.png)

**Comment by aimixess** [comment]
Hi,

Same problem here with awesomewm 
![2021-11-10-123422_45x28_scrot](https://user-images.githubusercontent.com/1127744/141106126-b65444e6-b292-4058-aec8-c0e786507d59.png). I also launch it with -t option but the tooltip is still appearing.

**Comment by cyberpunkrocker-zero** [comment]
Same issue here. On my Arch desktop (Awesome), the icon turned black, which is a very bad idea, because I'm using very dark grey as a systray background. On my Arch laptop (i3), the icon turned white.

In going to stick with pasystray-0.7.1 until this is fixed...

What was the big idea behind the change, anyway?

**Comment by christophgysin** [comment]
Can you check if this is caused by using symbolic icons? E.g. by commenting out the lines:
https://github.com/christophgysin/pasystray/blob/master/src/ui.c#L155-L158

**Comment by aimixess** [comment]
Hi,

I tried and have the white icon back
![2021-11-11-221638_52x28_scrot](https://user-images.githubusercontent.com/1127744/141370198-cfe3e4d4-5701-49ed-a267-da8716793fbf.png).

It also solve the problem I had wit -t switch but not in the right way : tootltip is not working with or without.

**Comment by arash-rohani** [comment]
> Can you check if this is caused by using symbolic icons? E.g. by commenting out the lines: https://github.com/christophgysin/pasystray/blob/master/src/ui.c#L155-L158

That fixed the color issue for me as well.

**Comment by sbbddz** [comment]
Works for me after removing the code lines mentioned earlier!

**Comment by christophgysin** [comment]
Could someone test if PR #153 fixes it? It should use the standard icons by default, and only use the symbolic ones when started with `--symbolic-icons`.

**Comment by aimixess** [comment]
> Could someone test if PR #153 fixes it? It should use the standard icons by default, and only use the symbolic ones when started with `--symbolic-icons`.

I just pull and compile again and icon is still white, it seems to work.

**Comment by arash-rohani** [comment]
The branch works correctly. But I just realized something. The problem with symbolic icon appearing as black even though we are using a dark theme is panel specific. Because I was not using another systray application that uses symbolic icons I never noticed that. For example "tint2" panel doesn't respect the dark theme when using symbolic icons but when I tested the exact same thing for "xfce4-panel" and "i3bar" they show the white symbolic icons. 
If @christophgysin wants to make symbolic icons the default from now on, as long there's an option to opt out (like `--no-symbolic-icons`) it should be fine. Either way works.

**Comment by cyberpunkrocker-zero** [comment]
IMHO no program should ever _force_ users to use symbolic icons, there should always be an option.

**Comment by jfly** [comment]
Excellent point, @arash-rohani! I did some digging, and it turns out that this is really just a bug with my tray manager (polybar): https://github.com/polybar/polybar/issues/2235. So I'm not sure that `pasystray` really should make any changes here. Instead, if there are other tray managers with similar bugs, they should just get fixed.

@cyberpunkrocker-zero I'm not sure I agree: at the end of the day, it seems to me that it should be up to the application developers to decide what their application should look like. If anything, symbolic icons are nice because they give the end user some flexibility in how they end up being displayed.

**Comment by fuelen** [comment]
I have the same issue with xmobar

**Comment by jfly** [comment]
@fuelen that can't be right: xmobar doesn't actually have support for systray icons. Are you using something else in addition to xmobar?

**Comment by fuelen** [comment]
ah, you're right. I use stalonetray with enabled transparency, so I have black icon on almost black background

**Comment by jfly** [comment]
IMO, that's a bug/missing feature with stalonetray. It should be able to set up this `_NET_SYSTEM_TRAY_COLORS` hint for you to tell tray icons what color they should be.

**Comment by psamim** [comment]
I have the same problem using awesomewm.

**Comment by jfly** [comment]
@psamim that also sounds like a bug/missing feature in awesomewm, but I guess they're aware of this issue, and it doesn't sound like they're interested in supporting it =( https://www.mail-archive.com/awesome@naquadah.org/msg05924.html.

**Comment by christophgysin** [comment]
It sounds like lots of apps still have issues with symbolic icons. I'm happy to default back to the normal icons and let users opt-in to symbolic icons. :+1: or :-1: ?

**Comment by arash-rohani** [comment]
@christophgysin I think that would be best. The silver lining is that so many bugs were found because of this update!

**Comment by jfly** [comment]
Yeah, I didn't know anything about symbolic icons before this change!

**Comment by n-peugnet** [comment]
I had this problem using DWM with the systray patch. As a workaround I added this rule to my GTK css `.config/gtk-3.0/gtk.css`:

```css
window > image {
        color: #ddd;
}
```

I guess it has to be tweaked depending on the DE or panels.

**Comment by linnabraham** [comment]
@n-peugnet Thanks a bunch man....Solved my issue as well.

**Comment by karthanistyr** [comment]
@christophgysin perhaps could we hope for a minor release with this fix ? :pray:

**Comment by OrionRandD** [comment]
> I have the same problem using awesomewm.

I have the same problem using pasystray on mode-line...
pasystray just disappeared from the right-top icons...
after a right-now upgrade on my debian system
10 min. ago, before the upgrade, it was showing up...
Fortunately, I can still call pavucontrol through Alt-F2
Something is not right with pasystray app...

**Comment by liskin** [comment]
I fixed this via https://github.com/liskin/dotfiles/commit/e26f782f54b765447c260b58461d4c2a0c7a01d0, and other people fixed it via https://github.com/nbarrientos/dotfiles/commit/e4dc6ec9b265d5959ed91060e83cb21067ebf8d2

**Comment by OrionRandD** [comment]
> I fixed this via [liskin/dotfiles@e26f782](https://github.com/liskin/dotfiles/commit/e26f782f54b765447c260b58461d4c2a0c7a01d0), and other people fixed it via [nbarrientos/dotfiles@e4dc6ec](https://github.com/nbarrientos/dotfiles/commit/e4dc6ec9b265d5959ed91060e83cb21067ebf8d2)

Thx

**Comment by kocv59** [comment]
> I had this problem using DWM with the systray patch. As a workaround I added this rule to my GTK css `~/.config/gtk-3.0/gtk.css` to change the color of the symbolic icons:
> 
> window > image {
>         color: #ddd;
> }
> 
> I guess it has to be tweaked depending on the DE or panels.

pasystray --symbolic-icons uses a dark icon which isn't visible on a dark background. What css can make it light? This one doesn't do it.
