### ISSUE TITLE
Keyboard shortcuts?

### ISSUE THREAD

**Issue by sonalys** [christophgysin/pasystray#157]
The default sys icon for pulseaudio in i3 `pa-applet` has bindings with dunst and keyboard shortcuts, would it be in the scope of this project to also add keybindings?

**Comment by aidan-hall** [comment]
Key bindings can be enabled with the `-g` option, and notifications should be on by default, but can also be enabled with `--notify=all`.

**Comment by sonalys** [comment]
it would be nice to add the parameters to readme maybe?

**Comment by christophgysin** [comment]
Indeed. Would you like to make a PR?

**Comment by sonalys** [comment]
sure, but I can't push branches.

**Comment by christophgysin** [comment]
@sonalys Not here, but on your own fork. See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
