### ISSUE TITLE
Symbolic icons problem

### ISSUE THREAD

**Issue by YanDoroshenko** [christophgysin/pasystray#160]
Not sure this is the right place to report this, but maybe someone can give me some advice on how to fix it.

I have an issue with symbolic icons, for some reason the icon doesn't respect the dark theme (the non-symbolic one does):

![image](https://user-images.githubusercontent.com/13915536/162694417-81fafa22-77ef-4233-8d8d-a4f49dfe7e80.png)

This only happens in DWM, in Openbox it works fine.

**Comment by christophgysin** [comment]
Possible duplicate of #151?

**Comment by YanDoroshenko** [comment]
Yes, it is. Here's a solution:
https://github.com/christophgysin/pasystray/issues/151#issuecomment-985911322

Thanks for the reply!
