### ISSUE TITLE
Regression: incorrect icon used in 8.0

### ISSUE THREAD

**Issue by konomikitten** [christophgysin/pasystray#161]
Currently on Debian (XFCE specifically) when updating to 8.0 the icon looks like this:
![pasystray 0 8 0](https://user-images.githubusercontent.com/12713710/176911745-60f192fd-86ff-439b-9167-6cba62bb4ab3.png)

In previous versions in this case 0.7.1 the icon looks like this:
![pasystray 0 7 1](https://user-images.githubusercontent.com/12713710/176911847-40c304f2-3926-4b5a-9443-a7c728532a7b.png)

I'm pretty sure my theme is set correctly so I'm not sure what's going on I can provide more debugging information if needed.

**Comment by christophgysin** [comment]
Duplicate of #151 ?

**Comment by konomikitten** [comment]
Version 0.8.1 was uploaded to Debian Unstable today and the icon problem is gone thanks for fixing this!
