### ISSUE TITLE
Important: gtk_widget_event: assertion ... failed

### ISSUE THREAD

**Issue by aarondill** [christophgysin/pasystray#173]
Error on popup open / mouse interaction with popup:
```
gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed`
```

I've bisected and traced this back to this commit: 58d5a2b9a5d24d93919a8bf3fe5dc11ab498c877

Reproduction:
```shell
> make && ./src/pasystray
... (make output)
# Click on icon
(pasystray:41701): Gtk-CRITICAL **: 02:43:23.549: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
... (Repeated)
```

This error is thrown for every time a key is pressed, or the popup is moused over.

Also, after clicking the icon, I can't click outside the popup to close it anymore, and the escape key only works to close it if I mouse over the popup before I press it.

**Comment by aarondill** [comment]
This might actually be an upstream: https://gitlab.gnome.org/GNOME/gtk/-/issues/885

However, if there's anything we can do *here* to improve this, it would be greatly appreciated, as this issue makes `pasystray` nearly unusable in my case.

**Comment by christophgysin** [comment]
Thanks for reporting, I'll revert the change.
