### ISSUE TITLE
Add native wayland support [enhancement]

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [christophgysin/pasystray#180]
This is not a bug report and more of a enhancement, most of the applets I use can work on wayland natively, I was wondering if there were any plans for pasystray to work on wayland natively? Currently if it is ran, it runs under xwayland, but it working natively work be a improvement for a variety of reasons, that being said, this is no a demand but a request and there might be technical limitations I might be unaware about.

**Comment by christophgysin** [comment]
See issue #90 and PR #171
