### ISSUE TITLE
missing tray icon?

### ISSUE THREAD

**Issue by vedantk** [christophgysin/pasystray#2]
pasystray displays a missing tray icon image in the systray. How can I make it display something less jarring?

Here's a screenshot; http://i.imgur.com/6THwU.png

In pasystray.desktop, it looks like Icon=pulseaudio. Changing that doesn't work.

thanks

**Comment by someshkoli** [comment]
Facing the same :\ Installed via aur, have a pasystray.png at /usr/share/pixmaps  and pulseaudio.svg at /usr/share/icons/hicolor/apps
here's the ss
![image](https://user-images.githubusercontent.com/41543649/234219119-a094d8dc-e90b-4454-adca-dc7398652c02.png)
any ideas  ?

**Comment by linuxdevman** [comment]
Are you sure you have a Notification area/applet and not just an XApp_Status area/applet?

**Comment by someshkoli** [comment]
@linuxdevman not sure about the diff, but rest of the applet icons are functional properly :thinking: even pasystray is working fine its just that the icon is missing
