### ISSUE TITLE
Does not reconnect if server exits

### ISSUE THREAD

**Issue by fsateler** [christophgysin/pasystray#32]
If I kill and restart pulseaudio, pasystray becomes useless until I restart it, because it no longer has any connection to a server.

**Comment by christophgysin** [comment]
It's a known problem:
https://github.com/christophgysin/pasystray/blob/master/TODO#L5

Patches welcome!

**Comment by fsateler** [comment]
:)

On 4 May 2015 at 17:02, Christoph Gysin <notifications@github.com> wrote:

> Closed #32 <https://github.com/christophgysin/pasystray/issues/32> via
> c48550d
> <https://github.com/christophgysin/pasystray/commit/c48550d94e0888a001f97dde6eadcb38ef607da3>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christophgysin/pasystray/issues/32#event-296596223>.
>



-- 

Saludos,
Felipe Sateler
