### ISSUE TITLE
Hovering mouse over some modules in the menu causes flickering display

### ISSUE THREAD

**Issue by ackalker** [christophgysin/pasystray#34]
Using pasystray 0.5.2 on Arch Linux (AUR package)
When I hover my mouse over certain module names in the Modules submenu, I'm seeing rapidly flickering ghost images of what must be the module info window. The flickering stops (and normal module info window shows) when I move my mouse to another module name.
This happens with the following module names, all of which are near the top of the module list:

module-device-restore
module-stream-restore
module-augment-properties

The problem does not occur with any of the other module names.

**Comment by christophgysin** [comment]
I can't seem to reproduce that.

**Comment by ackalker** [comment]
I've tried to record a screencast using Istanbul but sadly that doesn't record the module info windows at all, only the menu.
Perhaps it is a graphics toolkit glitch, but I must say I haven't seen it in any other application I've used.

**Comment by christophgysin** [comment]
It's weird that it only happens to certain modules. When hovering over a module, GTK should display the tooltip that was set for that item. That tooltip gets updated whenever there is a change event from pulseaudio. So I wonder if you somehow recieve loads of change events on those modules?

Is there any output from the command ```pactl subscribe``` when you see the flickering?

**Comment by ackalker** [comment]
Thanks for your quick reply :)

Besides one 'new' event and one 'change' event, there wasn't a flood of events during the flickering windows (thanks for the very handy command btw!).

I now have seen the flickering in two other applications, and I'm starting to believe it has to do with something else than pasystray, probably an interaction GTK* and video drivers (I'm using "the blob" from Nvidia, sadly).

Anyways, thank you for taking the time to help me out with this, much appreciated.

**Comment by christophgysin** [comment]
You're welcome, sorry I couldn't help.

I'm closing this, as it seems unrelated to pasystray.
