### ISSUE TITLE
Please update Launchpad to 5.2 and create an Indicator

### ISSUE THREAD

**Issue by Mannshoch** [christophgysin/pasystray#36]
It seems the dconf entry for the panel do not exist any more.
so I'm not able to whitelist it.

**Comment by christophgysin** [comment]
pasystray is nowadays shipped in the ubuntu universe repository. Please ask ubuntu developers to update their package to the latest version.

Also, the current version is supporting appindicator. If that is not working for you please file a bug for that separately.
