### ISSUE TITLE
start pavucontrol by clicking status icon

### ISSUE THREAD

**Issue by studentiks** [christophgysin/pasystray#37]
Hello! Thank you for pasystray. 

It would be great if Volume Control could be started with Left mouse Click on icon. Is this possible? 

Somewhere in systray.c, line 340:
 /* on left-click, show menu */ => /* on left-click, open Volume Control */

**Comment by christophgysin** [comment]
Left mouse button is already used to open the menu. But I can add a binding with a modifier, e.g. Ctrl + left mouse button.

This will only work when using the GtkStatusIcon though, not with AppIndicator.

**Comment by studentiks** [comment]
Dear Christoph, having both right-click and left-click for context menu feels somewhat redundant. IMHO it would be logical that left click should open volume meter and right click for context menu. But You are The Author =) Thank you!

**Comment by selurvedu** [comment]
> Dear Christoph, having both right-click and left-click for context menu feels somewhat redundant. IMHO it would be logical that left click should open volume meter and right click for context menu. But You are The Author =) Thank you!

This is the only reason I don't use pasystray daily. :(
