### ISSUE TITLE
[Feature request] Support connection with Kodi

### ISSUE THREAD

**Issue by Mannshoch** [christophgysin/pasystray#39]
Please support Kodi to output Audio on it  or get it from there.
Kodi: https://github.com/xbmc/xbmc
Pulseaudio and Airplay: https://bbs.archlinux.org/viewtopic.php?id=156135 (see Last Post)

**Comment by christophgysin** [comment]
This isn't the place to implement support for AirPlay. pasystray is just a graphical frontend for pulseaudio. If pulsaudio detects AirPlay devices, you should be able to see them in pasystray too.

It seems that pulseaudio supports Airplay with the module-raop-discover and module-raop-sink, and AirPlay2 with [pulseaudio-raop2](http://hfujita.github.io/pulseaudio-raop2). Please give those a try instead.
