### ISSUE TITLE
Please add mouse scroll increment/decrement option

### ISSUE THREAD

**Issue by Yanpas** [christophgysin/pasystray#40]
Scrolling over tray icon changes volume just a little bit. Add option or change scroll behavior or change increment size. 15-20 scrolls to change volume from 0 to 100 will be enouth

**Comment by christophgysin** [comment]
Could you please test if this works for you?

**Comment by Yanpas** [comment]
Yes, it works, BUT there two details:
* If I scroll up when volume is 100, the variable grows higher then 100. So I may scroll to 200, 300. Increasing must stop after reaching 100 per cents. Scrolling lower then 0 doesn't work, so it's good
* If increment is set more then 100 - notification is small, I guess program must crash, if "-i" variable is set more then 100
Built on 15.04 xubuntu. Tested on Xubuntu 15.04 and Mint 17.2 XFCE (3.16 kernel, based on 14.04). 
Tons of thanks again for your work :smile_cat: Your app is really the one which provides PA tray volume mixer.

**Comment by christophgysin** [comment]
Increasing the volume past 100% is a feature, not a bug. It is extremly handy when listening to very quiet sources, as you can simply amplify the output by increasing the volume past 100%. pavucontrol allows you to increase up to 153%, but that is really just an artificial limit set by the application. Pulseaudio has no such restriction, and neither does pasystray.

If you wish to limit the volume to a maximum value:
```
pasystray -m 100
```
I don't see why we would need to limit the maximum increment. Negative values are already being ignored.

**Comment by Yanpas** [comment]
OK, so I don't see bugs anymore, absolutely fixed :)
