### ISSUE TITLE
Please add posibility to disable notification event

### ISSUE THREAD

**Issue by Yanpas** [christophgysin/pasystray#41]
Please add posibility to disable notification, which is showing sink/source, volume in per centage etc. 

PS There are no tray mixers for pulseaudio currenly, so with this option it would be ideal solution. Pasystray only duplicates xfce4-volumed notifications

**Comment by christophgysin** [comment]
Could you please test if this works for you?

**Comment by Yanpas** [comment]
Yep, now I'll build and test last two commits

**Comment by Yanpas** [comment]
Yes, it works. Built on 15.04 xubuntu. Tested on Xubuntu 15.04 and Mint 17.2 XFCE (3.16 kernel, based on 14.04). Works!
