### ISSUE TITLE
Is It Possible to Change the Icon Colour from Gray to White?

### ISSUE THREAD

**Issue by alexbooker** [christophgysin/pasystray#43]
I am using [_i3wm_](https://i3wm.org/) and my bar's background colour is virtually the same as the pasystray icon, which makes the tray icon hard to see. 

Is it at all possible to change the tray icon colour to say, white?

**Comment by alexbooker** [comment]
I just noticed the icon is only gray if it is very small. If I increase the icon size, it turns white.

**Comment by christophgysin** [comment]
The icons are coming from your GTK icon theme.

Can you provide the configuration to reproduce the issue?

**Comment by alexbooker** [comment]
- I am using the [_Moka icon theme_](http://samuelhewitt.com/moka/icons).
- I am using i3wm
- The relevant portion of my bar configuration is as follows:
```
bar {
  font pango: System San Francisco Display, FontAwesome 11
}
```

I fixed the problem by making the bar taller:

```
bar {
  font pango: System San Francisco Display, FontAwesome 11
   height: 25
}
```

**Comment by christophgysin** [comment]
i3wm does no support setting the bar height. Are you using a patched version or a fork of it?

Also, Moka icon theme does not seem to provide icons for audio-volume-{muted,low,medium,high}.

**Comment by alexbooker** [comment]
My bad. I am using i3 gaps.

**Comment by christophgysin** [comment]
Closing this, as it can be fixed by increasing the bar height, or overriding the icon in the relevant icon theme.
