### ISSUE TITLE
Over status icon "mouse actions" do not work

### ISSUE THREAD

**Issue by JacekHoleczek** [christophgysin/pasystray#44]
This is KDE Ubuntu 14.04.3 LTS / x86_64.
Over status icon "mouse actions" do not work at all except "right-click"
which opens the menu (even "left-click" and "middle-click" do not work).

**Comment by christophgysin** [comment]
This is a bug in AppIndicator, there is nothing I  can do in pasystray to fix this.  As stated in my email to you:

From:
https://github.com/christophgysin/pasystray/blob/master/README.md#troubleshooting
"For Ubuntu 13.04 and above, AppIndicator is mandatory. Unfortunately,
the ctrl + click / ctrl + scroll bindings don't work with
AppIndicator."

This is a limitation of AppIndicator. Please file a bug to request
support for it, and I'll happily implement it in pasystray:
https://github.com/christophgysin/pasystray/blob/master/src/systray_impl.c#L34

**Comment by christophgysin** [comment]
AppIndicator does not allow catching modifiers, or individual mouse buttons. It only provides a method to set a menu, and decides itself when it is shown.
See:
https://github.com/christophgysin/pasystray/blob/master/src/systray_impl.c#L46

**Comment by JacekHoleczek** [comment]
In KMix, all "left-click" (mixer), middle-click" (mute), right-click" (menu) AND "scroll" (volume up/down) do work.

**Comment by christophgysin** [comment]
Interesting. Looking at kmix, it seems to implement this with KDE's KStatusNotifierItem[1], which in turn is built on FDO's StatusNotifierItem[2].

[1] http://api.kde.org/frameworks-api/frameworks5-apidocs/knotifications/html/classKStatusNotifierItem.html
[2] http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/

**Comment by christophgysin** [comment]
Created a new Issue #47.

**Comment by christophgysin** [comment]
After more investigation it seems that this really needs to be fixed in AppIndicator.

**Comment by christophgysin** [comment]
If you care about this, file a bug in AppIndicator and report back when it is fixed:
https://bugs.launchpad.net/ubuntu/+source/libappindicator

**Comment by JacekHoleczek** [comment]
Sorry but I don't really know what to report. It's only you who knows what misbehaves in AppIndicator and so I think you are the only / best contact for them to talk about it.

**Comment by christophgysin** [comment]
I do not use Ubuntu / AppIndicator, and you are the only one who seems to care about that feature.

AppIndicator needs to emit signals for all methods of StatusNotifierItem. Currently it only emits `scroll-event` for method `Scroll`. For your feature, it also needs to emit signals for method `ContextMenu`, `Activate` and `SecondaryActivate`. See:
http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem
