### ISSUE TITLE
Vital devices are missing in "Recording Streams" for applications

### ISSUE THREAD

**Issue by JacekHoleczek** [christophgysin/pasystray#45]
This is KDE Ubuntu 14.04.3 LTS / x86_64.
Vital devices are missing in "Recording Streams" for applications (i.e.
all "Monitor of ..." devices) and the ordering of all available devices
needs to be fixed (they need to be sorted in the same order as they appear
in pavucontrol). These problems are exactly the same as reported here for
Mumble:
https://github.com/mumble-voip/mumble/issues/1910

See the following thread for the output of "pasystray --debug": https://github.com/christophgysin/pasystray/issues/46

**Comment by christophgysin** [comment]
Monitors are excluded on purpose, as they are not vital for most people. Your usecase might be different.

I could add a command line option to include monitors:
```
$ pasystray --include-monitors
```

**Comment by JacekHoleczek** [comment]
I think it should also be possible to "toggle" this setting from inside of the menu of a running pasystray.

**Comment by christophgysin** [comment]
I don't think so. If that's what you need, you should probably use pavucontrol instead.
