### ISSUE TITLE
Cannot change sinks / sources for applications

### ISSUE THREAD

**Issue by JacekHoleczek** [christophgysin/pasystray#46]
This is KDE Ubuntu 14.04.3 LTS / x86_64.
When I try to change the sinks / sources for applications, pasystray
modifies these settings in its menu but it does NOT execute these actions
(i.e. the real sinks / sources are not changed at all).
Please find attached the output of "pasystray --debug".

[pasystray.out.txt](https://github.com/christophgysin/pasystray/files/46617/pasystray.out.txt)

**Comment by christophgysin** [comment]
The log you attached only seems to contain the startup of pasystray. You need to reproduce the issue while `pasystray --debug`is running, then send the log.

**Comment by JacekHoleczek** [comment]
There is nothing else in the output.
I tried both:
"right-click" (menu) -> "Playback Streams" -> running_application -> "change to one of available streams"
"right-click" (menu) -> "Recording Streams" -> running_application -> "change to one of available streams"
and in both cases the change is visible in the sub-menu but nothing is really changed (i.e. the "running_application" is still using the same stream.

**Comment by christophgysin** [comment]
You might be changing the stream on a different pasystray instance. Stop it first, then try again:
```
$ killall pasystray
$ pasystray --debug
```
There should be a lot of output for pretty much every possible action in pasystray.

**Comment by JacekHoleczek** [comment]
[...]$ killall pasystray: 
no process foundpasystray

**Comment by christophgysin** [comment]
In the log you posted, it ends with 70 dashes. Pasystray did not write those. Can it be that you missed some output?

How about:
```
$ pasystray --debug > pasystray.log
```
Then reproduce the issue, and post the file `pasystray.log`.

**Comment by JacekHoleczek** [comment]
No, I manually added dashes in the beginning and in the end of this file as I thought I would need to paste its contents directly into the post. In the end it turned out that I can simply attach the whole file.

**Comment by christophgysin** [comment]
I don't understand how it is possible that "the change is visible in the sub-menu" without there being any actions visible in the logs. The former indicates that actions are executed, while the later seems to indicate they are not.

**Comment by sophie-kuehn** [comment]
I have the same issue. Sink is changed in the menu, sink is still the previous one looking into pavucontrol, nothing in the logs. 

Linux Mint 20.3 Cinnamon
Kernel 5.4.0-121-generic
using Pipewire
