### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Gfurst** [christophgysin/pasystray#48]
Hello, I'm on Arch Linux and build pasystray from the AUR. My current desktop is kde5 plasma, upon starting the app, it shows up on the tray but no actions at all happen, no right or left click, no scroll, completely blind.
Any hints to why this might be?

**Comment by CMCDragonkai** [comment]
I'm getting something similar here. Actually on KDE5, starting pasystray shows nothing, no icon on the systray. Starting it from the CLI shows: 

```
GConf Error: Failed to contact configuration server; the most common cause is a missing or misconfigured D-Bus session bus daemomn. See http://projects.gnome.org/gconf/ for information. (Details - 1: GetIOR failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GConf was not provided by any .service files.)
```

The program doesn't terminate.

**Comment by christophgysin** [comment]
@Gfurst:
I assume you are using AppIndicator. Please attach the output of ```pasystray --debug```.

@CMCDragonkai:
Please don't hijack issues, but create separate ones. It seems that your issue was fixed in NixOS.

**Comment by christophgysin** [comment]
Failed to provide debug output, closing.

**Comment by jadali17** [comment]
Hello! Same issue as the first guy, here's the debug output you requested : 
`(pasystray:5183): pasystray-WARNING **: 11:37:40.430: Error initializing Avahi: Daemon not running
(pasystray:5183): pasystray-DEBUG: 11:37:40.430: using UI file: /usr/share/pasystray/pasystray.gtk3.glade
(pasystray:5183): pasystray-DEBUG: 11:37:40.457: [systray_impl] using GtkStatusIcon
(pasystray:5183): pasystray-DEBUG: 11:37:40.463: [pulseaudio] connecting...
(pasystray:5183): pasystray-DEBUG: 11:37:40.464: [pulseaudio] authorizing...
(pasystray:5183): pasystray-DEBUG: 11:37:40.464: [pulseaudio] setting name...
(pasystray:5183): pasystray-DEBUG: 11:37:40.468: [menu_info] adding server 0 manjaro (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.469: [menu_info] adding sink 0 TU106 High Definition Audio Controller Digital Stereo (HDMI) (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.469: [menu_info] adding sink 1 Starship/Matisse HD Audio Controller Digital Stereo (IEC958) (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.469: [menu_info] adding sink 2 TU106 High Definition Audio Controller Digital Stereo (HDMI) (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.469: [menu_info] adding sink 3 Starship/Matisse HD Audio Controller Analog Stereo (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.469: pulseaudio_update_systray_icon(alsa_output.pci-0000_29_00.4.analog-stereo)
(pasystray:5183): pasystray-DEBUG: 11:37:40.469: pulseaudio_set_volume_icon(alsa_output.pci-0000_29_00.4.analog-stereo)
(pasystray:5183): pasystray-DEBUG: 11:37:40.469: volume:56065
(pasystray:5183): pasystray-DEBUG: 11:37:40.470: [menu_info] adding source 1 HyperX Amp Mono (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.470: [menu_info] adding source 4 HyperX Amp Mono (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.470: [menu_info] adding module 0 module-device-restore (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.470: [menu_info] adding module 1 module-stream-restore (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 2 module-card-restore (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 3 module-augment-properties (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 4 module-switch-on-port-available (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 6 module-alsa-card (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 7 module-alsa-card (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 8 module-alsa-card (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 9 module-jackdbus-detect (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 10 module-bluetooth-policy (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.471: [menu_info] adding module 11 module-bluetooth-discover (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 12 module-bluez5-discover (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 13 module-dbus-protocol (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 14 module-native-protocol-unix (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 15 module-gsettings (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 16 module-default-device-restore (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 17 module-always-sink (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 18 module-intended-roles (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 19 module-suspend-on-idle (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 20 module-console-kit (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 21 module-systemd-login (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 22 module-position-event-sounds (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 23 module-role-cork (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.472: [menu_info] adding module 24 module-filter-heuristics (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.473: [menu_info] adding module 25 module-filter-apply (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.473: [menu_info] adding module 26 module-cli-protocol-unix (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.473: [menu_info] adding module 27 module-udev-detect (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.473: [menu_info] adding module 28 module-alsa-card (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.473: [menu_info] adding module 29 module-alsa-card (target: -1)
(pasystray:5183): pasystray-DEBUG: 11:37:40.473: [menu_info] adding module 30 module-alsa-card (target: -1)
`

**Comment by christophgysin** [comment]
Pleas use the AppIndicator backend, and if that doesn't work open a new issue.
