### ISSUE TITLE
Include volume level in menu items for streams, sinks, sources

### ISSUE THREAD

**Issue by Woowoo678** [christophgysin/pasystray#50]
The ability to control the volume of individual streams etc was an excellent addition to _pasystray_ (no more mucking about in pavucontrol!). Tracking what one actually sets the volume to, though, is more cumbersome. The only apparent way to check an individual item's volume currently is to hover over it for a second, and scan through that enormous info bubble that pops up.

Instead of all that, it'd be convenient just to have the volume level represented right there on the menu item, either through a simple percentage display or even the addition of a horizontal slider.

**Comment by Woowoo678** [comment]
Another prospect for volume display may be showing the percentage/slider when right-clicking the menu item.

**Comment by christophgysin** [comment]
If you have compiled in support for notifications, you can see the volume levels there. Depending on how those are displayed, I can see that this is not very intuitive though.
