### ISSUE TITLE
Manipulating stream volume only works after left-clicking

### ISSUE THREAD

**Issue by Woowoo678** [christophgysin/pasystray#51]
Simply hovering the cursor over a playback stream's respective menu item and scrolling/middle-clicking does nothing to change the stream's volume; these functions only work after one or two left-clicks on the item.

Since I don't really use a microphone, I don't know if the same applies for recording streams, but I would assume that it does.

**Comment by christophgysin** [comment]
Simply hovering over a stream opens the submenu. It seems that only after clicking the item the scroll events get forwarded to the stream menu item. This seems to be a limitation in gtk, and should be reported upstream.

If there is any workaround, let me know, and I'll happily implement it.

**Comment by rightaway** [comment]
Also the percentage volume display doesn't get updated.
