### ISSUE TITLE
Long menu items cause very wide menus

### ISSUE THREAD

**Issue by smlx** [christophgysin/pasystray#58]
Bug reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761053

As described in the title, having a source/sink/stream with a very long description causes the width of the menu to become too large (i.e. larger than the screen).

You can reproduce this issue by adding a null sink with a very long description:

    $ pactl load-module module-null-sink sink_name=ANYNAME sink_properties=device.description="<insert a long string here>"

Now open up the pasystray sink menu.

And remove the sink again via:

    $ pactl unload-module module-null-sink

I guess pasystray should have a maximum menu size (possibly related to detected screen size)?

Thanks!

**Comment by christophgysin** [comment]
The maximum size should probably be a lot smaller than the screen size. If the sink/source/output/input names are longer than N chars we should cut the end and replace it with the ellipsis character (…).

What would be an acceptable value for N? N=80?

**Comment by smlx** [comment]
80 sounds reasonable to me (I guess until someone comes along with a lower resolution screen :P)

You already have the tooltip/popup showing full details on the item, so eliding characters after 80 in the menu should still allow disambiguation (in the case that the first 80 characters are the same between multiple sinks).
