### ISSUE TITLE
Add menu item to move all streams to selected device

### ISSUE THREAD

**Issue by Harvie** [christophgysin/pasystray#59]
Hello,
i use pasystray to select default device, however when i have some playback stream that has started before switching the device i want some dead simple way to move all streams to desired device. Maybe there can be just tick box that will set if all streams should be moved to device when changing default device. so i can easily set if the default device will be used only for new streams, or even for the streams already playing.

**Comment by c0d3z3r0** [comment]
Currently the systray icon does not get updated when the default sink gets changed.
It tried to fix that but pasystray crashes... maybe @christophgysin knows, how to do that right..

Non-working patch:
~~~
diff --git a/src/menu_info.c b/src/menu_info.c
index f78c017..6b7f61f 100644
--- a/src/menu_info.c
+++ b/src/menu_info.c
@@ -561,8 +561,10 @@ void menu_info_subitem_clicked(GtkWidget* item, GdkEventButton* event,
             break;
         case MENU_SINK:
             pulseaudio_move_input_to_sink(mii->menu_info->parent, mii);
-            if(mis->settings.sync_default)
-                pulseaudio_set_default(mii);
+            if(mis->settings.sync_default) {
+              pulseaudio_set_default(mii);
+              ui_update_systray_icon(mii);
+            }
             break;
         case MENU_SOURCE:
             pulseaudio_move_output_to_source(mii->menu_info->parent, mii);
~~~

Error:
~~~
(pasystray:17914): pasystray-DEBUG: [systray] click mod: button:1
(pasystray:17914): pasystray-DEBUG: [menu_info] subitem clicked mod: button:1
(pasystray:17914): pasystray-DEBUG: [pulseaudio_action] move input Spotify 100% to sink Built-in Audio Analog Stereo  70%
(pasystray:17914): pasystray-DEBUG: pulseaudio_update_systray_icon(alsa_output.pci-0000_00_1f.3.analog-stereo)
(pasystray:17914): pasystray-DEBUG: pulseaudio_set_volume_icon(alsa_output.pci-0000_00_1f.3.analog-stereo)
(pasystray:17914): pasystray-DEBUG: volume:0 muted
Assertion 'a' failed at pulse/volume.c:90, function pa_cvolume_avg(). Aborting.
Aborted (core dumped)
~~~

**Comment by christophgysin** [comment]
If you get a coredump, please open it with gdb and print a backtrace.
```
$ gdb src/pasystray core
(gdb) bt
```
Or on systems with systemd/coredumpctl:
 ```
$ coredumpctl gdb pasystray
```

**Comment by c0d3z3r0** [comment]
It crashes in ui.c in line 56 at "pa_volume_t volume = pa_cvolume_avg(mii->volume);" since the volume is NULL...

**Comment by c0d3z3r0** [comment]
I found the problem.. systray_add_all_items_to_submenu does not set the volume for subitems, so either .. systray_add_all_items_to_submenu should set subitem->volume  or ui_set_volume_icon should look up the main item from the sinks hashtable.
That fixes the crash but the icon does not get updated correctly. Maybe that is the wrong place to do the update or something else is bad.

**Comment by Harvie** [comment]
Thanks! Can't wait to test it :)

**Comment by Notakas** [comment]
Where can I find this menu item? I can only change the streams one by one.

**Comment by Harvie** [comment]
Right click on desired sink:

![image](https://user-images.githubusercontent.com/276504/65911578-1e707c80-e3cd-11e9-9261-2d8d4a9794ef.png)
