### ISSUE TITLE
When changing the default sink the icon is not updated properly

### ISSUE THREAD

**Issue by Harvie** [christophgysin/pasystray#64]
How to reproduce:

1.) have two sinks (one muted one umuted)
2.) change default sink from muted to unmuted
3.) tray icon is still muted untill i mute and unmute it again using middle click

This works even for sinks with different volume settings, however on mute it's easiest to be seen as you can clearly tell the muted icon from normal.

**Comment by christophgysin** [comment]
Thanks for reporting the issue, should be fixed now!

**Comment by Harvie** [comment]
Works for me now! Thanks.
