### ISSUE TITLE
Notification is not fired when changing volume using 3rd party app.

### ISSUE THREAD

**Issue by Harvie** [christophgysin/pasystray#65]
When i change volume from some 3rd party app, eg. from commandline:

`amixer -q -D pulse set Master 5%- unmute`

icon updates, but no notification is shown. i am not sure how good idea this is, but i guess it can be usefull when i'll map volume keys on my keyboard to call amixer to adjust volume. But i guess, it may be obtrusive in some cases.

Another solution (may be even better) is implementing support for changing volume using keyboard shortcuts directly in pasystray...

**Comment by christophgysin** [comment]
Did you start  pasystray with ```--always-notify```?

**Comment by Harvie** [comment]
oh, sorry, thanks :)
