### ISSUE TITLE
tar.gz release 0.6.0 is missing man page

### ISSUE THREAD

**Issue by czerw** [christophgysin/pasystray#67]
Pasystray releases on GitHUB release page have different content

There are three download options:
1. pasystray-0.6.0.tar.gz -> https://github.com/christophgysin/pasystray/releases/download/pasystray-0.6.0/pasystray-0.6.0.tar.gz 
2. Source code (zip) -> https://github.com/christophgysin/pasystray/archive/pasystray-0.6.0.zip
3. Source code (tar.gz) -> https://github.com/christophgysin/pasystray/archive/pasystray-0.6.0.tar.gz

Unfortunately, option "1" has different content than others, it has no man directory, also the size of tar.gz file is double than other options.

**Comment by christophgysin** [comment]
Can you use option 3?

Option 1 is a tarball create using autotools (which seems to need some tweaking to include the man page). Option 2 and 3 are archives genereated by github directly from the source tag.

**Comment by czerw** [comment]
No problem, option 3 is fine. It was just confusing to found that files are different.
Would be possible to remove option from release download page?

**Comment by christophgysin** [comment]
Removed.
