### ISSUE TITLE
Support for System Sounds (Libcanberra)

### ISSUE THREAD

**Issue by Xylemon** [christophgysin/pasystray#68]
Something I've felt is missing from pasystray is that in the playback streams menu, "System Sounds" is absent. You should see it in pavucontrol's Playback tab and be able to control the volume. If I am correct, it's just an integration of Libcanberra. Could the same functionality be added in pasystray?

**Comment by christophgysin** [comment]
AFAIK, "System Sounds" in pavucontrol is only for event sounds created by pavucontrol. pasystray is not creating any event sounds, and therefore does not need that volume control.

I'll happily accept patches to support (optional) event sounds from pasystray though.
