### ISSUE TITLE
Segmentation fault when trying to change sink for Telegram Desktop

### ISSUE THREAD

**Issue by Woowoo678** [christophgysin/pasystray#72]
When changing the output sink for the Linux version of Telegram ( https://github.com/telegramdesktop/tdesktop ), Pasystray will close with a segmentation fault.

Notable also is the fact that attempting to perform this action in pavucontrol will also fail. In this case, the stream will continue to output to the original sink, and no errors are shown by the program.

**Comment by christophgysin** [comment]
Could you provide a backtrace of the segfault?

**Comment by Woowoo678** [comment]
This is what I got from running it in gdb, if that is what you mean
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000408281 in pulseaudio_move_success_cb (c=0xdfd420, success=0, 
    userdata=0xe37fc0) at pulseaudio_action.c:125
warning: Source file is more recent than executable.
125	        g_warning("failed to move %s '%s' to %s '%s'!\n",
```
