### ISSUE TITLE
[Feature Request] List Programs on Pasystray

### ISSUE THREAD

**Issue by Mannshoch** [christophgysin/pasystray#74]
Please add a Menu which contain all Open Applications with Audio Output. Like pavucontrol do contain.

**Comment by smlx** [comment]
That is the Playback Streams menu.

-- 
Regards,
Scott.

**Comment by Mannshoch** [comment]
There I only get strange titles like "voll 86%" or "Cubebutils 97%" and a change of the Input there do nothing, only  pavucontrol works immediately.

**Comment by christophgysin** [comment]
As @smlx already mentioned, this is already implemented. You can see more details about the streams by hovering over the items.

If something does not work, report a bug separately.
