### ISSUE TITLE
change tray icon

### ISSUE THREAD

**Issue by chridazi** [christophgysin/pasystray#76]
is there any way to change the icon(s) pasystray is using in appindicator? as i recognized via strace it uses the standard gnome icon theme (by gtk_icon_theme_get_default()??) but i want it to use some icons of my favourite theme. i know it would be easy to change the icons in the gnome standard theme, but i want to leave this original. or does pasystray try to look in my favourite theme, maybe can't find the relevant icons and fall back to the gnome standard icon theme? so maybe there's a way to integrate the needed icons in my favourite theme? btw, i'm using version 0.4 in xubuntu 16.04. many thanks for any answer.

**Comment by christophgysin** [comment]
Pasystray gets the icon from your current icon theme, using [gtk_icon_theme_get_default()](https://developer.gnome.org/gtk3/stable/GtkIconTheme.html#gtk-icon-theme-get-default).

You might want to ask the xubuntu community how to change the icon theme or override individual icons.
