### ISSUE TITLE
qpaeq

### ISSUE THREAD

**Issue by rshadow** [christophgysin/pasystray#77]
Please add support for pulseaudio-equalizer:

Home page: [equalizer](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Equalizer/)

**Comment by christophgysin** [comment]
Trying to load `module-equalizer-sink` gives:

```
W: [pulseaudio] module-equalizer-sink.c: module-equalizer-sink is currently unsupported, and can sometimes cause PulseAudio crashes, increased latency or audible artifacts.
```

It seems that equalizer isn't supported anymore by pulseaudio.
