### ISSUE TITLE
Sink/Source rename failing

### ISSUE THREAD

**Issue by Woowoo678** [christophgysin/pasystray#78]
Whenever I try to rename a sink or source, I only get an empty window, with the following debug messages:
```
(pasystray:18942): pasystray-DEBUG: [menu_info] item clicked mod: button:3

(pasystray:18942): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(pasystray:18942): Gtk-CRITICAL **: gtk_entry_set_text: assertion 'GTK_IS_ENTRY (entry)' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by christophgysin** [comment]
I managed to reproduce this, then deleted `~/.pulse/*-device-manager.tdb` and now I can't reproduce it anymore :(

Can you still reproduce this? What if you delete device manager DB?

**Comment by Woowoo678** [comment]
There seems to be no such `~/.pulse/` directory on my system, nor does the file exist in `~/.config/pulse/`. Anywhere else this file might be located?

**Comment by christophgysin** [comment]
It seems that this broke after trying to make the glade file gtk2 compatible.

Can you try if reverting 14b4bceb138f3764c5f879e71540b161c0982039 fixes this for you?

**Comment by Woowoo678** [comment]
Looks like that does it, yes
