### ISSUE TITLE
Use C99 fixed width types instead of `gint`

### ISSUE THREAD

**Issue by sakshamsharma** [christophgysin/pasystray#84]
I don't know if there is a reason for preferring `gint` over `int32_t` et all. A quick search confirms my thoughts that gint is obsolete now (ever since we moved past C99), as explained [here](http://stackoverflow.com/questions/13821332/why-is-it-better-to-use-glib-data-types-e-g-gint-instead-of-int).

I note [this commit](https://github.com/christophgysin/pasystray/commit/dd344cfd25328af8aab0deebd12287d37b25d218) which introduced the header for this.

If this change is not acceptable, then perhaps could you please clarify a bit on the availability of gint? The reason I am filing this issue is that pasystray has stopped compiling on my Gentoo (at least via the package manager, which compiles everything from source in Gentoo) ever since release 0.6.0. Here's the error:
```
In file included from notify.c:26:0:
notify.h:30:77: error: unknown type name ‘gint’
 notify_handle_t notify(const char* msg, const char* body, const char* icon, gint value);
                                                                             ^
notify.h:31:92: error: unknown type name ‘gint’
 void notify_update(notify_handle_t h, const char* msg, const char* body, const char* icon, gint value);
```

I suppose `gint` is not that portable as was expected. For information, I am on `glib-2.48.2`.

**Comment by lmiphay** [comment]
Try the ebuild here: https://github.com/lmiphay/gentoo.overlay/blob/master/media-sound/pasystray/pasystray-0.6.0-r2.ebuild

For reference the gentoo bug is here: https://bugs.gentoo.org/show_bug.cgi?id=605246

I added the explicit dep on glib after seeing the gint problem - I think I found that there were other glib dependencies (e.g. the pulse audio glib library).

**Comment by christophgysin** [comment]
Since the whole codebase is using glib, I see no benefit replacing all types with the `stdint.h` equivalents.

That `gint value` later gets passed to `notify_notification_set_hint_int32`, which has the signature:
```c
void notify_notification_set_hint_int32 (NotifyNotification *notification, const gchar *key, gint value)
```

**Comment by christophgysin** [comment]
Since the original problem is a missing dependency in a gentoo ebuild, I'm closing this.

**Comment by sakshamsharma** [comment]
Thanks for the quick reply!
Stupid me, I hadn't noticed the disabled `libnotify` useflag in my installation. It works by enabling that. Although I think Gentoo should make it compulsory, and this is primarily a bug with the packaging, my personal opinion would favor `int32_t` over the arcane `gint` for obvious reasons (and because that removes a compulsory dep). Feel free to close this issue if that's not something you'd like. Else, I can PR or you can change yourself :smile:
