### ISSUE TITLE
No HiDPI support?

### ISSUE THREAD

**Issue by UnicodeAlt255** [christophgysin/pasystray#86]
I'm running pasystray with i3 with `xrandr --dpi 215` for my 4k screen. However, the pasystray interface seems unaffected and is tiny and unusable.

**Comment by christophgysin** [comment]
pasystray uses GTK for displaying the interface. Try setting GDK_SCALE in the enviroment:
```
$ GDK_SCALE=2 pasystray
```

**Comment by UnicodeAlt255** [comment]
yeah that works
