### ISSUE TITLE
Scroll to adjust volume of playback streams

### ISSUE THREAD

**Issue by Fiona** [christophgysin/pasystray#97]
Hi I've just discovered this and I love it! Being able to adjust the volume of devices and switching stream devices replaces almost everything I use pavucontrol for.

Unfortunately the other thing is adjusting volume of streams directly. It would be wonderful if it was possible to adjust the volume of streams in the same way we can for devices.

**Comment by thetoastcaper** [comment]
You should be able do do this after first clicking on the stream's menu item! I think it's 'cause of some issue with GTK, but I wouldn't really know.

**Comment by Meister1593** [comment]
I noticed that if i click it works right, but the volume % isn't changing in menu (i can see notify about changing sound volume)
This is also related to gtk?

**Comment by christophgysin** [comment]
I believe that's what I described in https://github.com/christophgysin/pasystray/issues/51#issuecomment-203913935?

If you think this is a different problem, feel free to open another issue, with a detailed explanation, steps to reproduce, debug output etc.
